version: 2.1

# CircleCI docs on variables:
# https://circleci.com/docs/2.0/env-vars/

jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
              docker build .
